version: '3.9'

services:
  mongo:
    build: 
      context: ./db
    ports:
      - "27017:27017"
    networks:
      - app-network

  builddb:
    build: 
      context: ./builddb
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    networks:
      - app-network

  mapapp:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - builddb
    networks:
        - app-network

networks:
  app-network: